server:
  port: 3344

spring:
  application:
    name: cloud-config-server #注册到eureka的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TateTang/springcloud-config.git # git仓库地址
          search-paths:
            - springcloud-config # 搜索目录
          default-label: master # 读取分支
  #rabbitmq相关配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


#暴露监控端口，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

