server:
  port: 8002 #服务端口
spring:
  application:
    name: cloud-payment-service #服务名：注入eureka的服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://116.62.79.24:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: '@Tmffsj1314'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tate.springcloud.entities  #所有entity别名所在包


eureka:
  client:
    register-with-eureka: true # true表示向注册中心注册自己 默认true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖当前地址
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # eureka集群中
  instance:
    instance-id: payment8002 # 实例名称
    prefer-ip-address: true # 访问路径可以显示ip地址



