server:
  port: 80

eureka:
  client:
    register-with-eureka: false #false表示不向eureka注入自己
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ # eureka集群中

#设置 feign客户端超向( openfeign默认支持 ribbon)
ribbon:
  #指的是建立连接所用的所向,适チ努状況正常胸パ两端近接所用的
  Readtimeout: 5000
  #指的是立连接后从务器读到別资源所用的时向
  Connecttimeout: 5000
